version: "3.9"

services:
  web:
    build:
      context: ./docker/backend
      dockerfile: Dockerfile
    restart: always
    container_name: flask
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    environment:
      FLASK_DEBUG: 'True'
      MONGO_INITDB_ROOT_USERNAME: erik1288
      MONGO_INITDB_ROOT_PASSWORD: ingeniero010

  redis:
    build:
      context: ./docker/database
      dockerfile: Dockerfile
    restart: always
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - data_redis:/data

  redisinsight:
    image: redislabs/redisinsight
    container_name: redisinsight
    ports:
      - 8001:8001
    volumes:
      - redisinsight_data:/db
  
volumes:
  data_redis:
  redisinsight_data: